### ISSUE TITLE
Not Able to Get List of Tag in AB A

### ISSUE THREAD

**Issue by ricky5151** [libplctag/libplctag.NET#114]
I am working on a project to get the list of tag available inside a AB PLC controller. The tag available is shown in the diagram below.
![image](https://user-images.githubusercontent.com/35485764/102975283-c4f8ee00-453a-11eb-92ea-6cd830e7086f.png)

In this project, I am using ethernet connection to connect PLC with my laptop. The IP was 192.168.236.20. Below is the code that I deployed to get list of tags.

`var tags = new Tag<TagInfoPlcMapper, TagInfo[]>()
            {
                Gateway = "192.168.236.20",
                Path = "1,0",
                PlcType = PlcType.ControlLogix,
                Protocol = Protocol.ab_eip,
                Name = "TestDINTArray[0]"
            };
            tags.Read();

            ConsoleTable
                .From(tags.Value.Select(t => new
                {
                    t.Id,
                    Type = $"0x{t.Type:X}",
                    t.Name,
                    t.Length,
                    Dimensions = string.Join(",", t.Dimensions)
                }))
                .Configure(o => o.NumberAlignment = Alignment.Right)
                .Write(Format.Default);`

However, when I run the program, I got nothing in result. What is the possible root cause of this?

**Comment by timyhac** [comment]
The tag name is wrong, it should be @tags.
