### ISSUE TITLE
Issue with reading from Tag-Based alarms in a ControlLogix PLC

### ISSUE THREAD

**Issue by darko-liberati** [libplctag/libplctag.NET#117]
I found an issue with the original libplctag code where it would not allow you to read from tag-based alarm tags. I notified the original developers/supporters of libplctag library and they have fixed the issue. I reached out to the c# wrapper library developer on github and they are no longer supporting their code and pointed me to here.

Can you include the new changes to the libplctag to this wrapper so that people can read tag-based alarms?

Thanks,

Here is the original thread from the original libplctag git-hub.

https://github.com/libplctag/libplctag/issues/222

**Comment by timyhac** [comment]
Is anything required beyond packaging the new core libplctag runtime?

**Comment by kyle-github** [comment]
Nope.  Just pick up 2.1.22.

**Comment by timyhac** [comment]
Hey there @darko-liberati - please use latest packages which reference the 2.1.22 runtimes.
