### ISSUE TITLE
Next steps for c# wrapper

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag.NET#12]
We should determine what the next steps are for the c# wrapper now that it has been incorporated into the libplctag organization.

I feel a good place to start with is agreeing on what the goals should be. Maybe these could be similar goals to wrappers for other languages, maybe not. I have some goals written on the README for this project but definitely open to changing these goals.

One issue with the current goals is that we can simplify how this works because we no longer have to support the ability for end-users to supply their own plctag dll with statically linked projects.

**Comment by timyhac** [comment]
@libplctag/c-sharp-wrapper - where is the best place to discuss this?

**Comment by kyle-github** [comment]
Maybe a kick off on the forum/email list followed by discussion in an issue here?  Or set up an issue with the question and announce it in the forum?   I find that doing both gets a lot more eyeballs.

**Comment by timyhac** [comment]
I created a topic here: https://groups.google.com/forum/#!topic/libplctag/6yWU9A2m0K4
