### ISSUE TITLE
UDT Converter

### ISSUE THREAD

**Issue by ricky-ge** [libplctag/libplctag.NET#128]
I have a list of tag variable in an UDT as shown below. For such case,  if I would like to create my own PlcMapper, is the code below correct? As the example used only involved in DINT, not SINT, therefore I would like to confirm if my written code is correct for this situation or not.

![image](https://user-images.githubusercontent.com/77655174/105810946-c8bedb00-5fe6-11eb-833f-bf1fd622909e.png)

```
var DINT0 = tag.GetInt32(0)
var DINT1 = tag.GetInt8(4)
var DINT2 = tag.GetInt8(5)

MoveIndex = DINT0;

BitArray bitArray1 = new BitArray(new int[] { DINT1 });
MoveAbsPB = bitArray1[31];
OS_MoveAbs = bitArray1[30];
...

BitArray bitArray2 = new BitArray(new int[] { DINT2 });
OS_Jog = bitArray2[31];
SV_OnPB = bitArray2[30];
...
```

**Comment by timyhac** [comment]
You can follow the other mappers for direction:
* https://github.com/libplctag/libplctag.NET/blob/master/src/libplctag/DataTypes/SintPlcMapper.cs#L8
* https://github.com/libplctag/libplctag.NET/blob/master/src/libplctag/DataTypes/TagInfoPlcMapper.cs
* https://github.com/libplctag/libplctag.NET/blob/master/src/libplctag/DataTypes/TimerPlcMapper.cs
* https://github.com/libplctag/libplctag.NET/blob/master/src/Examples/CSharp%20DotNetCore/SequencePlcMapper.cs
