### ISSUE TITLE
Reading/polling multiple tags for changes. 

### ISSUE THREAD

**Issue by darko-liberati** [libplctag/libplctag.NET#131]
I am trying to pull logix based alarms using the libplctag.NET frramework. I was wondering if anyone has had any success in creating the same technique that rockwell or other PLC vendors have where they create a Tagdatabase and constantly poll/update the values.
I don't know if this is something that libplctag.NET can do or if there are other software libraries and databases that are needed to have this functionality.

trying to basically recreate how win911 grabs tags for alarms and events.

**Comment by timyhac** [comment]
I'm not familiar with win911 or Tagdatabases but in terms of "constantly poll/update the values" you might find [auto-sync](https://github.com/libplctag/libplctag/wiki/Tag-String-Attributes#auto-sync) relevant.

Using Read/Write callbacks would probably be useful in this situation. This isn't exposed in the primary package, but you can use the NativeImport package to access this feature. Similar to [this](https://github.com/libplctag/libplctag.NET/blob/master/src/Examples/CSharp%20DotNetCore/NativeImportExample.cs#L47) example.

You can look at some old work that looked at incorporating events/callbacks here. This was the first attempt at implementing async support using callbacks, but isn't finished.
https://github.com/libplctag/libplctag.NET/blob/async/src/libplctag/Tag.cs#L77



In terms of "Reading/polling multiple tags _for changes_" - there is no built-in change detection feature.

In terms of "Reading/polling _multiple tags_" - you can make use of libplctags request packing functionality by using the asynchronous mode and reading multiple tags at once.
