### ISSUE TITLE
Possible typo in Array Example

### ISSUE THREAD

**Issue by TheFern2** [libplctag/libplctag.NET#149]
Not sure if this a bug, I am a bit rusty on C#, for a one dimension array, should it be ARRAY_LENGTH? I wasn't able to read a one dim array as per the example, started reading tags after removing one ARRAY_LENGTH. I can submit  PR if I am correct, or maybe I misunderstood the reason for two ARRAY_LENGTH.

https://github.com/libplctag/libplctag.NET/blob/master/src/Examples/CSharp%20DotNetCore/ExampleArray.cs#L30

```csharp
var dintTag = new Tag<DintPlcMapper, int[]>()
{
    Name = "TestDINTArray2",
    Gateway = gateway,
    Path = path,
    PlcType = PlcType.ControlLogix,
    Protocol = Protocol.ab_eip,
    ArrayDimensions = new int[] { ARRAY_LENGTH, ARRAY_LENGTH },
    Timeout = TimeSpan.FromMilliseconds(TIMEOUT),
};
```

**Comment by timyhac** [comment]
I think you are correct - thanks, I have updated the example.
