### ISSUE TITLE
Generic C# wrapper to read the template of all structured tags

### ISSUE THREAD

**Issue by jochen-haar** [libplctag/libplctag.NET#165]
All,

please find below the link to a conversation I've placed regarding this topic. In that conversation you will find the C# wrapper class.

Kyle asked me to raise this issue, as the wrapper could be helpful once Kyle finalized his structured tag solution in the library.

Link: https://groups.google.com/g/libplctag/c/juEsM1hywi0/m/Kw9klmfHAQAJ

Best regards
Jochen

**Comment by timyhac** [comment]
This is supported as of libplctag.NET libplctag v1.0.10
