### ISSUE TITLE
How Set Debug level 

### ISSUE THREAD

**Issue by nainesh72** [libplctag/libplctag.NET#167]
var myTag = new Tag<DintPlcMapper, int>()
{
    Name = "PROGRAM:SomeProgram.SomeDINT",
    Gateway = "10.10.10.10",
    Path = "1,0",
    PlcType = PlcType.ControlLogix,
    Protocol = Protocol.ab_eip,
    Timeout = TimeSpan.FromSeconds(5)
};

// Read the value from the PLC
myTag.Read();

// Output to Console
Console.WriteLine(myTag.Value);

How i set Debug level Here
Thanks

**Comment by timyhac** [comment]
The debug level is global so you set it using the LibPlcTag static class: https://github.com/libplctag/libplctag.NET/blob/master/src/libplctag/LibPlcTag.cs

**Comment by nainesh72** [comment]
Hi
Thanks For Support I new i C# coding so ones again i thanks you

**Comment by nainesh72** [comment]
Hi
Thanks For Support I new i C# coding so ones again i thanks you
