### ISSUE TITLE
Expose new libplctag APIs

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag.NET#17]
New APIs are available in the core dll. Expose these functions to end users.

**Comment by timyhac** [comment]
Started work on this - see https://github.com/libplctag/libplctag.NET/tree/new-API

**Comment by kyle-github** [comment]
Thanks, Timy (is it Timy, timyhac, Timy Hac? what do you want to be
called?),

The callbacks are probably the hardest part now.   Is there something I can
do to make those better?   Everything else has very simple data types
(intentionally) such as int32 and C-style strings.

Best,
Kyle

**Comment by timyhac** [comment]
timyhac probably (my real name is Tim and I've just kept this email address
for ages).

I've just pushed some new example code to the new-APIs branch which checks
the callbacks - see
https://github.com/libplctag/libplctag.NET/blob/new-API/src/ConsoleTest/NativeImportExample.cs
The event callback seems to be working, but I don't know how to check the
logging callback - how can I generate a log?

**Comment by timyhac** [comment]
Figured it out, you have to set a debug level in the attribute string. Seems like it works.

**Comment by kyle-github** [comment]
Sorry, I must have missed this yesterday :-(

You can set a debug level in the attribute string or you can call `plc_tag_set_debug_level()`.   Setting it to PLCTAG_DEBUG_INFO or PLCTAG_DEBUG_DETAIL will give you plenty of output.  Do not use PLCTAG_DEBUG_SPEW unless you want to test your IO subsystem :-)

Best,
Kyle

**Comment by timyhac** [comment]
This is done as part of c61f68a064fff7f33e5e93147498fa80f73dc2af
