### ISSUE TITLE
Pulling whole tag list

### ISSUE THREAD

**Issue by th3dj** [libplctag/libplctag.NET#180]
I am having issues with trying to pull the whole tag list. I looked at the C# versions and I think I supposedly have it right.

        Me.tags = New Tag(Of TagInfoPlcMapper, TagInfo)() With {
            .Name = "@tag",
            .Protocol = 0,
            .Gateway = ip,
            .PlcType = PlcType.ControlLogix,
            .Path = path
        }
The error I'm coming back with is:
Type argument 'TagInfoPlcMapper' does not inherit from or implement the constraint type 'IPlcMapper(Of TagInfo)'.

I am kinda new to using this library so i9 apologize if this is a stupid question

**Comment by timyhac** [comment]
İt needs to be a Tagİnfo array, not a single Tagİnfo.

**Comment by timyhac** [comment]
Also, `@tags` not `@tag` - please see the example code here: https://github.com/libplctag/libplctag.NET/blob/master/src/Examples/CSharp%20DotNetCore/ExampleListTags.cs

**Comment by th3dj** [comment]
Thank you, I appreciate the help in the matter!
