### ISSUE TITLE
Error with SetInt8() and SetUInt8()

### ISSUE THREAD

**Issue by joao147** [libplctag/libplctag.NET#181]
I'm integrating Omron-nj-nx series on a SCADA and using Tag(it isn't Tag<M, T>) to read/write all Get/Set all types are working perfectly, expect set to Sint(byte).
![image](https://user-images.githubusercontent.com/50873876/124974253-f59a0400-e002-11eb-9fd9-7a5caa6ffe5f.png)

**Comment by timyhac** [comment]
Hi @joao147 thanks for the feedback.

Are you able to confirm this by using the native API? Something like the Run() method in this example: https://github.com/libplctag/libplctag.NET/blob/master/src/Examples/CSharp%20NativeImport/NativeImportExample.cs#L9

**Comment by joao147** [comment]
Hello @timyhac thank you to answer really quickly,

I tried as you said, but continue return error 29. The thing that I think really strange is GetInt8 and GetUInt8 are work correct.
![image](https://user-images.githubusercontent.com/50873876/125278512-389cf580-e2e9-11eb-885e-36e5066cd85e.png)

**Comment by timyhac** [comment]
Thanks for confirming. This means that it's an issue with the core project, or i guess an issue with your device. Are you able file a bug on the core project?

**Comment by joao147** [comment]
Ok, I tried to use a old wrapper that we have here from core project and receive the same error, just telling you, I going to open a issue on core project, maybe they know if an error with my device or core project. 
Thank for listening.

**Comment by timyhac** [comment]
Thanks @joao147
