### ISSUE TITLE
Implement INotifyPropertyChanged in a TAG

### ISSUE THREAD

**Issue by Naihan** [libplctag/libplctag.NET#185]
Hi 
I've been using the following [example ](https://github.com/libplctag/libplctag.NET/blob/master/src/Examples/CSharp%20DotNetCore/SequencePlcMapper.cs)

I'm to watch the UDT tag when it changes (running periodically reads) and I'm using  INotifyPropertyChanged interface,
The problem is that the Decode Method in the SequencePlcMapper returns a new instance of the tag.
is there a way to preserve the same tag reference so i can use INotifyPropertyChanged  ?

Thanks!

**Comment by timyhac** [comment]
PlcMapper classes return the _value_ of a tag, not the tag object itself.
İf you need the instance to be the same, you would somehow need to retain an instance in between calls to Decode - couldnt you add a provide a private field and store it there?
