### ISSUE TITLE
Support `plc_tag_set_size()`

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag.NET#195]
The new v2.4.0 has support for raw CIP tags, which may require setting the size via the new API `plc_tag_set_size(...)`

**Comment by kyle-github** [comment]
Nice work!  I think that libplctag.NET is really the official face of the project now!

**Comment by timyhac** [comment]
After a big screw-up with the git history on this change, this should be supported in libplctag.NativeImport v1.0.17 and libplctag v1.0.11
