### ISSUE TITLE
Issue with ReadAsync returning the call for the System.Runtime.CompilerService method, instead of the tag value.

### ISSUE THREAD

**Issue by redsuinit** [libplctag/libplctag.NET#241]
I know I was just here two days ago, BUT I have another small issue. Whenever I try to call the ReadAsync method I get something like this returned:

System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.String,CLPLCTagWrapper.AllenBradley+<ReadDIntAsync>d__22]
 
Instead of the tag value.

Example Code:

        private async Task<object> ReadDIntAsync(string PLCAddress, string PLCPath, PlcType plcType, Protocol protocol, string TagName, int timeout)
        {
            var myTag = new Tag<DintPlcMapper, int>()
            {
                Name = TagName,
                Gateway = PLCAddress,
                Path = PLCPath,
                PlcType = plcType,
                Protocol = protocol,
                Timeout = TimeSpan.FromSeconds(timeout)
            };

            // Read the value from the PLC
            await myTag.ReadAsync();
            return myTag.Value;
        }

Now this may somehow be a self inflicted issue, I just don't know how that would be the case.

I'm on the latest stable build for both the libtagplc.NativeImport and libtagplc.net libraries.

The Read() method works just fine.

**Comment by kyle-github** [comment]
Anything we could learn from and use to drive changes into one or more of the library layers?   Even if it is just better error output!
