### ISSUE TITLE
ExampleListTags Issue with console table

### ISSUE THREAD

**Issue by LastKnownHero** [libplctag/libplctag.NET#250]
I have a Winforms app that I am trying to learn with, I can populate tags to a list with a value but when I try using some of the example files I get errors in the code supplied:

![image](https://user-images.githubusercontent.com/103644216/163388916-eb1bdf4f-9c12-413f-8956-e87884a14ce6.png)

**Comment by timyhac** [comment]
I think its the .NET version you're targeting, .NET Framework doesn't seem to have the right overload - so you'll need to explicitly convert ToString().

Given that you're using WinForms, why are you using ConsoleTable?
