### ISSUE TITLE
Writing strings

### ISSUE THREAD

**Issue by AndyMedtronic** [libplctag/libplctag.NET#251]
I would be grateful for assistance on writing strings when ControlLogix Buffer Length < 88
(As a matter of interest I thought default for AB ControlLogix = 82)
e.g. attempt to write String40 
        public void WriteStringTag(string tagName, string stringValue, int buffLength)
        {
            var stringTag = new Tag<StringPlcMapper, string>()
            {
                Name = $"{tagName}",
                Gateway = _ipAddress,
                Path = "1,0",
                PlcType = PlcType.ControlLogix,
                Protocol = Protocol.ab_eip,
            };
            stringTag.Write(stringValue);
        }

Fails
Note the buffLength param  is not used here
Some guidance as to the correct way to do this would be gratefully received

**Comment by timyhac** [comment]
@AndyMedtronic - there was some conversation about this issue with a solution here: https://github.com/libplctag/libplctag.NET/issues/240#issuecomment-1034187365
