### ISSUE TITLE
VB.NET example fails

### ISSUE THREAD

**Issue by raentzmi** [libplctag/libplctag.NET#258]
When running the VB.NET example it produces an exception.

Exception thrown: 'libplctag.LibPlcTagException' in libplctag.dll
An unhandled exception of type 'libplctag.LibPlcTagException' occurred in libplctag.dll
ErrorBadParam

To correct this you need to add the following:
Add the following:
        Dim myTag = New Tag(Of DintPlcMapper, Integer)() With
        {
            .Name = "SomeDINT",
            .Gateway = "192.168.88.143",
            .Path = "1,0",
            .PlcType = PlcType.ControlLogix,
    ---->.Protocol = Protocol.ab_eip,
            .Timeout = TimeSpan.FromSeconds(5)
        }

**Comment by jkoplo** [comment]
Right you are!

Fixed in: #260
