### ISSUE TITLE
How create an event from PLC ?

### ISSUE THREAD

**Issue by patopat** [libplctag/libplctag.NET#267]
Hi,

I would like on event from the PLC to trig a recording. Is there a way to create an event or I have to poll the flag with read() ?

Regards,
Pat

**Comment by timyhac** [comment]
Have you tried the AutoSyncRead feature with the ReadCompleted event?
https://github.com/libplctag/libplctag/wiki/Tag-String-Attributes#auto-sync

**Comment by patopat** [comment]
Hi @timyhac,

It's a feature from LibPlcTag, is it available in .NET ?

Regards,
Pat

**Comment by timyhac** [comment]
It looks like it is available in the latest alpha release
