### ISSUE TITLE
Match UDT to Tags

### ISSUE THREAD

**Issue by johncharris** [libplctag/libplctag.NET#268]
I see how to get the UDTs and Tags, but how can I know when a tag is of a UDTs type? The I expected the Tag's type to match the UDT id or handle, but neither seem to match. How are these associated?

**Comment by timyhac** [comment]
Please study this example which should explain how that relationship works:
https://github.com/libplctag/libplctag.NET/blob/master/src/Examples/CSharp%20DotNetCore/ListUdtDefinitions.cs

**Comment by timyhac** [comment]
@johncharris - I trust that you were able to make sense of this?

**Comment by johncharris** [comment]
Yes, I got it all figured out. I think I wasn't matching things with the GetUdtId bitmasking. Thank you.
