### ISSUE TITLE
Reading strings out of range exception

### ISSUE THREAD

**Issue by MilDur** [libplctag/libplctag.NET#269]
Hello,
   im trying to read strings from PLC. But for some of them im getting argument out of range exception. Can you help me figure out whats wrong?
Thanks

**Comment by timyhac** [comment]
@MilDur - you will need to post more information so that we can help you. Without context its hard to know what information would be useful but to start with, can you tell us the following:
* What hardware are you using?
* What code have you tried?
* Where is the exception being thrown?
