### ISSUE TITLE
Better readme/description in Nuget package

### ISSUE THREAD

**Issue by jkoplo** [libplctag/libplctag.NET#283]

**Comment by timyhac** [comment]
I did not think about this ticket before releasing the package.

FYI it looks like we can include both a description and a README and we could potentially just include one we already use. https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile

**Comment by timyhac** [comment]
README files have been added for both the [libplctag](https://www.nuget.org/packages/libplctag)and [libplctag.NativeImport](https://www.nuget.org/packages/libplctag.NativeImport) packages.
