### ISSUE TITLE
The process cannot access the file 'plctag.dll' 

### ISSUE THREAD

**Issue by avnet78** [libplctag/libplctag.NET#290]
I am using the libplctag.net library. The source code build is deployed on windows 11 server. I’m using dotnet framework version 452.
I have two windows  services or deamon processes.  One reads values from the ethernet IP device and the other one writes values to the ethernet IP device.  Both processes are running simultaneously.
I don’t have any issues with the reads but the writes are throwing exception saying that the DLL is being used by another process. 
If I stop the read process, I see that the writes happen without issues. 
Please advise.

**Comment by timyhac** [comment]
Set plctag.ForceExtractLibrary = false before any other calls to libplctag

**Comment by timyhac** [comment]
@avnet78 - did this solve your problem?

**Comment by dresslerc** [comment]
I had same issue.  Did the plctag.ForceExtractLibrary = false and it worked.

Just side note, had to bring in:

`using libplctag.NativeImport;`

**Comment by avnet78** [comment]
Yes, it worked for me.

**Comment by timyhac** [comment]
Thanks for the update
