### ISSUE TITLE
CompactLogix Plc Communicate C# this code not working on compactlogix

### ISSUE THREAD

**Issue by swetabhardwaj26** [libplctag/libplctag.NET#330]
using libplctag;
using libplctag.DataTypes;
using Microsoft.VisualBasic;

namespace PLC_Communication
{
    public partial class Form1 : Form
    {
        Tag<DintPlcMapper, int> Test_Dint;
        Tag<RealPlcMapper, float> Test_Real;
        public Form1()
        {

            InitializeComponent();

            //Init Tag
            Test_Dint = new Tag<DintPlcMapper, int>()
            {
                Name = "Test_Dint",
                Gateway = "192.168.29.1",
                Path = "1,0",
                PlcType = PlcType.ControlLogix,
                Protocol = Protocol.ab_eip,
                Timeout = TimeSpan.FromSeconds(5)
            };
            Test_Real = new Tag<RealPlcMapper, float>()
            {
                Name = "Test_Real",
                Gateway = "192.168.29.1",
                Path = "1,0",
                PlcType = PlcType.ControlLogix,
                Protocol = Protocol.ab_eip,
                Timeout = TimeSpan.FromSeconds(5)
            };

            //Thread
            Thread plcUpdateThread=new Thread(new ThreadStart(plcThread));
            plcUpdateThread.Start();
        }

        void plcThread()
        {
            while (true)
            {
                Test_Dint.Read();
                Test_Real.Read();
                int temp = Test_Dint.Value;
                float temp2=Test_Real.Value;
                tempField.Text = Convert.ToString(Convert.ToString(temp2));
                dintField.Text = Convert.ToString(temp);
            }
        }

        private void dintField_TextChanged(object sender, EventArgs e)
        {
            status.Text = "Value Update";
        }
        private void change2_Click(object sender, EventArgs e)
        {
            string input=Interaction.InputBox("Input Value", "Input new Value");
            if(input != null)
            {
                int val;
                if (Int32.TryParse(input, out val))
                {
                    Test_Dint.Value = val;
                   Test_Dint.Write();
                } else
                {
                    MessageBox.Show("Invalid Input", "Invalid Input", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
    }
}

**Comment by timyhac** [comment]
Why do you say it is not working? For example; Does it fail to compile? Are there some exceptions thrown? Is there something you expect to happen that is not happening?

Here is some guidance on how to create an issue: https://github.com/libplctag/libplctag.NET/blob/master/CONTRIBUTIONS.md#guidance-when-creating-an-issue
