### ISSUE TITLE
Can I read descriptions from tags

### ISSUE THREAD

**Issue by th3dj** [libplctag/libplctag.NET#332]
I know that with the addition of extended tags way back when are we able pull descriptions at this time?

**Comment by timyhac** [comment]
If it is possible in libplctag core it should be accessible for libplctag.NET wrapper users.

There is an issue on the core project here around this: https://github.com/libplctag/libplctag/issues/358

**Comment by th3dj** [comment]
Oh neat. I will have to try that soon.
