### ISSUE TITLE
What does error not allowed mean? 

### ISSUE THREAD

**Issue by kaptindan** [libplctag/libplctag.NET#333]
So I can read a tag for a photo eye trigger which is a local tag. When i try to write to it I get a error not allowed.

**Comment by timyhac** [comment]
> PLCTAG_ERR_NOT_ALLOWED (-18) - often returned from the remote system when an operation is not permitted.

https://github.com/libplctag/libplctag/wiki/API#status-codes

**Comment by kaptindan** [comment]
Come to find out I was looking around at the PLC code and that tag was a read only. The plc programmer had no idea it got changed. lol easy fix.
