### ISSUE TITLE
Why can't I read out the PLC data type after a "Read" although the data type is supplied with the read?

### ISSUE THREAD

**Issue by joed74** [libplctag/libplctag.NET#344]
Why can't I read out the PLC data type after a "Read" although the data type is supplied with the read?

```        
var btag = new Tag
     {
                Gateway = gateway,
                Path = "1,0",
                PlcType = PlcType.ControlLogix,
                Protocol = Protocol.ab_eip,
                Timeout = new TimeSpan(0, 0, 0, 0, 250),
                Name = "HMI_Administration.PData.ToHmi.EnableLoadNext"
      };
      btag.Read();
      btag.Type ???
```

According to the wireshark answer the datatype is supplied with the value:

![grafik](https://github.com/libplctag/libplctag.NET/assets/61152521/d21696a9-8981-4beb-89d8-92c782b15a55)

c1 is the datatype, bool

**Comment by timyhac** [comment]
İf that ever becomes possible in core libplctag, it will be exposed to the .NET wrapper - see this ticket for discussion
https://github.com/libplctag/libplctag/issues/252

**Comment by timyhac** [comment]
@joed74  - please chime in on that other ticket with your use case. I will close this ticket out as its primarily a core libplctag concern.
