### ISSUE TITLE
Read Performance for Numerous Tags

### ISSUE THREAD

**Issue by noumanqaiser** [libplctag/libplctag.NET#345]
This library is an amazing peice of work, Thank you for this.

I had a question about read performance. In the application I am working on, I need to read >100tags from a PLC very often(every second). 

I understand that the Tag.Read() function would create an underlying connection with plc, read that tag and close the connection. When reading a large number of tags, would constantly opening/closing connection add in to the time needed/compute resources on PLC end? 

To make this read process efficient, Is there a way that you can keep a connection open while you read a ton of tags and then close at once?

**Comment by timyhac** [comment]
That assumption is incorrect - libplctag will keep a TCP and an EIP connection open in between successive calls.

Performance is often discussed here so you should be able to find other info around. Here is one post that is relevant: https://github.com/libplctag/libplctag/issues/413#issuecomment-1426545823
