### ISSUE TITLE
Is it possible to use libplctag.NET for reading and writing tags in Siemens S7-1200?

### ISSUE THREAD

**Issue by jojobs** [libplctag/libplctag.NET#364]
Is it possible to use libplctag.NET for reading and writing tags in Siemens S7-1200?

**Comment by kyle-github** [comment]
If that PLC only supports the S7 protocol, then no.   If it supports CIP or Modbus, then yes.  I hope that helps.

**Comment by jojobs** [comment]
Thanks v much @kyle-github. Siemens S7-1200 PLCs typically use S7 communication protocol for data exchange, so I will go for s7netplus.
