### ISSUE TITLE
Array tag notification on change

### ISSUE THREAD

**Issue by Primabase** [libplctag/libplctag.NET#367]
Hi,

it's possible to be notified when an array tag will change? 
I've tried to modify the example ExampleNotifyChanged.cs adding then property ArrayDimensions. 

Thanks.

**Comment by timyhac** [comment]
The library doesn't do anything to provide value change detection - you'll need to write some code to somehow compare previous values to current values.

The most generic way would be to read the buffer into a byte array, run a hashing function, and then store and compare the hash, but of course there are issues with this - hash collisions being one of them.
