### ISSUE TITLE
How to batch read multiple tags at once?

### ISSUE THREAD

**Issue by 313843288** [libplctag/libplctag.NET#373]
AB PLC，How to batch read multiple tags at once？

**Comment by kyle-github** [comment]
If the PLC supports it, the library does this automatically if it has multiple tags with outstanding requests.  The simplest way to make sure that this happens is to create several tags and then trigger reads or writes on all of them without a wait time.  This triggers the operation in the background.  Once they are all triggered, then just wait on all of the tags.

**Comment by kyle-github** [comment]
I am not a C# programmer, but I think the code at the [indicated section](https://github.com/libplctag/libplctag.NET/blob/e92962ffc2d51951140703576ade44b22d9a8264/src/LibplctagReadBenchmark/ReadExamples.cs#L21) does the async read of multiple tags.

**Comment by 313843288** [comment]
thank you!
