### ISSUE TITLE
Allow `AutoSyncReadInterval` and `AutoSyncWriteInterval` to be set after tag is Initialized

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag.NET#383]
Most tag attributes are only used during the creation of the tag object, but some can be [configured afterwards](https://github.com/libplctag/libplctag/blob/release/src/lib/lib.c#L2035):
1. `read_cache_ms`
2. `debug_level`
3. `auto_sync_read_ms`
4. `auto_sync_write_ms`

Currently, libplctag.NET wrapper allows 1 and 2 to be set but prevents 3 andd 4 by throwing an exception.

Having the ability to set these at runtime can be useful for interactive applications that need to change the update frequency.

Notes:
* It may be preferable to just allow all attributes to be configured after Initialize, and let the core library make the determination of whether this is sensible or not.
* These two tag attributes are not shown in the core library documentation in the [tag-internal-attribute-functions](https://github.com/libplctag/libplctag/wiki/API#tag-internal-attribute-functions) section.

**Comment by kyle-github** [comment]
Oops.  They are documented now!  Thanks for noticing they were missing!

I should come up with something a bit more coherent for how attributes are described so that it is clear which ones can be changed at runtime.
