### ISSUE TITLE
Expose `max_requests_in_flight` on `Tag` or `Tag<M,T>`.

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag.NET#384]
`max_requests_in_flight` is currently not exposed to `Tag` or `Tag<M,T>`.

It is a [modbus-specific attribute](https://github.com/libplctag/libplctag/wiki/Tag-String-Attributes#modbus-specific-attributes).

This issue requests that is is exposed for those classes.

I think it [is possible](https://github.com/libplctag/libplctag/blob/release/src/lib/lib.c#L2111) for this attribute to be configured after the tag has been Initialized.
Note, it may be preferable to just allow all attributes to be configured after Initialize, and let the core library make the determination of whether this is sensible or not.

**Comment by kyle-github** [comment]
It would be difficult to make this work when setting it lower at runtime.  It could orphan some requests.   Setting it higher could possibly work but is probably not a good idea.  I think it is best to make this one only work at creation time.

**Comment by kyle-github** [comment]
BTW, this is exposed in the wiki section on type-specific attributes.  This is a bit of a mess, isn't it?

**Comment by timyhac** [comment]
> It would be difficult to make this work when setting it lower at runtime. It could orphan some requests. Setting it higher could possibly work but is probably not a good idea. I think it is best to make this one only work at creation time.

Yes no problem I can check for this. I'm more thinking that it might make more sense to let the core library decide what can be changed after creation time and just pass through the error - rather doing that logic in the wrapper.


> BTW, this is exposed in the wiki section on type-specific attributes.

This is where I saw it - I imagine that this has been there for some time, not sure how I missed it.

**Comment by timyhac** [comment]
This has been released in [libplctag v1.5.0](https://github.com/libplctag/libplctag.NET/releases/tag/libplctag-v1.5.0)
