### ISSUE TITLE
CI doesn't embed native runtimes

### ISSUE THREAD

**Issue by timyhac** [libplctag/libplctag.NET#41]
Latest two builds (that used github actions) don't include the native runtimes (and therefore don't work).

**Comment by jkoplo** [comment]
I saw you published a .27-alpha03, any luck?

**Comment by timyhac** [comment]
Not yet - I'm just fiddling with the CI to see why its not building. Seems like there are a whole bunch of dotnet cli bugs out there around this.

**Comment by timyhac** [comment]
Fixed with 1b83e72
