### ISSUE TITLE
GetBuffer(byte[] buffer) Not working

### ISSUE THREAD

**Issue by dnmalenke** [libplctag/libplctag.NET#421]
Seems like the function here:
https://github.com/libplctag/libplctag.NET/blob/a4ebff5ba60946e1af0fc53e6f30f269a3d973a3/src/libplctag/Tag.cs#L907-L916
does not fill the provided buffer. 
It just reads the bytes into a temp buffer.

Line 914 can be updated to:
```
var result = (Status)_native.plc_tag_get_raw_bytes(nativeTagHandle, offset, buffer, length);
```

Maybe add a check to prevent reading more than the tag's size if a buffer larger than the tag is passed in?

**Comment by kyle-github** [comment]
The underlying core DLL will not copy more data than is in the tag's internal buffer.

**Comment by timyhac** [comment]
Yes good find.
Looks like I messed this up during the big changes in #407.

It should be as it was after #394 was merged

**Comment by timyhac** [comment]
@dnmalenke - should be fixed with in main branch.
